num_lst = [value for value in range(2, 8)]
print(num_lst)
num_lst.append('Python')
print(num_lst)
print(num_lst[0])
print(num_lst[-1])
print(num_lst[2:5])
print(len(num_lst))
print(num_lst.index(6))
num_lst.remove('Python')
print(num_lst)
